### ISSUE TITLE
Looking forward to adding the following features in future versions

### ISSUE THREAD

**Issue by hildoszlengq** [hopskipnfall/EmuLinker-K#111]
1. Network disconnection reconnects
2. Join the game halfway through
3. Join room password

**Comment by hopskipnfall** [comment]
Hi hildoszlengq thanks for the suggestions.

The room password is definitely doable, but I'm not clear what the use case would be. Since the room owner can already kick people from the room, this doesn't seem like it would be that helpful. I'm open to being convinced otherwise though.

Being able to recover from dropped packet failures would be great. Being able to recover from desyncs is impossible without client-side and protocol changes which I'm not in a position to be able to do.

Joining mid-game would also be cool, though that would require protocol changes and client-side changes. And would only work with certain emulators, so I'm not sure if we will get that feature in Kaillera.
